# Generated by Django 3.2.9 on 2022-01-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('open', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
