# Generated by Django 3.2.9 on 2022-02-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='notification_list',
        ),
        migrations.AddField(
            model_name='person',
            name='notification_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='notification', to='main.Stock'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='person',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlist', to='main.Stock'),
        ),
    ]
