# Generated by Django 3.2.9 on 2022-02-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220224_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='notification_list',
            field=models.ManyToManyField(blank=True, related_name='notification', to='main.Stock'),
        ),
        migrations.AlterField(
            model_name='person',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='main.Stock'),
        ),
    ]
