# Generated by Django 3.2.9 on 2022-02-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220227_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='in_notification_list',
            field=models.ManyToManyField(blank=True, related_name='in_notification_list', to='main.Person'),
        ),
        migrations.AddField(
            model_name='stock',
            name='in_watchlist',
            field=models.ManyToManyField(blank=True, related_name='in_watchlist', to='main.Person'),
        ),
    ]
